config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  get '/directors/(:director)/all_movies', to: 'movies#director_all_movies', as: 'director_all_movies'

  resources :movies
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  def self.all_ratings
    %w(G PG PG-13 R NC-17)
  end

  def self.find_by_director(director)
    if director != nil
      Movie.where(:director => director)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def self.sortable_attributes;
    %w(title release_date director rating)
  end

  def initialize
    @all_ratings = Movie.all_ratings
    @rating_selected = @all_ratings.map { |rating| [rating, true] }.to_h
    super
  end

  def movie_params
    params.require(:movie).permit(:title, :director, :rating, :description, :release_date)
  end

  def show
    id = params[:id]
    @movie = Movie.find(id)
    @director = @movie.director
  end

  def index
    @movies = Movie.all
    filter
    sort
  end

  def filter
    if params[:ratings]
      ratings = params[:ratings].keys
    elsif session[:filter]
      ratings = session[:filter]
    else
      ratings = nil
    end

    if ratings
      @movies.where!(rating: ratings)
      @all_ratings.each do |rating|
        @rating_selected[rating] = ratings.include? rating
      end
      session[:filter] = ratings
    end
  end

  def sort
    if params[:sort_by]
      sort_by = params[:sort_by]
    elsif session[:sort_by]
      sort_by = session[:sort_by]
    else
      sort_by = nil
    end

    if self.class.sortable_attributes.include?(sort_by)
      @movies.order!(sort_by)
      session[:sort_by] = sort_by
    end
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  # add in hw4
  def director_all_movies
    param_director = params[:director].to_s
    if not param_director.empty?
      @director = param_director
      @movies = Movie.find_by_director(@director)
      sort
      @title = @director
    else
      @director = nil
      @title = 'Not Found'
    end

    param_from = params[:from].to_s
    if not param_from.empty?
      @from_movie_id = param_from
      @from_movie = Movie.find(@from_movie_id)
    else
      @from_movie_id = nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title=content_for?(:title) ? yield(:title) : 'Rotten Potatoes!'
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/movies/_form.html.haml
= label :movie, :title, 'Title'
= text_field :movie, 'title'

= label :movie, :director, 'Director'
= text_field :movie, 'director'

= label :movie, :rating, 'Rating'
= select :movie, :rating, %w(G PG PG-13 R NC-17)

= label :movie, :release_date, 'Released On'
= date_select :movie, :release_date, :start_year => 1900, :end_year => Date.today.year

app/views/movies/_list.html.haml
%table#movies
  %thead
    %tr
      %th{class: ('hilite' if session[:sort_by] == 'title'), id: 'title_header'}= link_to('Movie Title', movies_path(sort_by: 'title'))
      %th{class: ('hilite' if session[:sort_by] == 'director'), id: 'director_header'}= link_to('Director', movies_path(sort_by: 'director'))
      %th{class: ('hilite' if session[:sort_by] == 'rating'), id: 'rating_header'}= link_to('Rating', movies_path(sort_by: 'rating'))
      %th{class: ('hilite' if session[:sort_by] == 'release_date'), id: 'release_date_header'}= link_to('Release Date', movies_path(sort_by: 'release_date'))
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title
        %td= movie.director
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

app/views/movies/director_all_movies.html.haml
- if @director.nil?
  - title_string= 'Not Found'
- else
  - title_string= @director

%head
  = content_for(:title, title_string + ' - Rotten Potatoes!')

- if @director.nil?
  - if @from_movie.nil?
    %p Please enter a valid director.
  - else
    %p= "'#{@from_movie.title}' has no director info."
- else
  %h1 #{@director}'s all movies

  - if @movies.nil? || @movies.length == 0
    %p= "\"#{@director}\" has no movies at Rotten Potatoes yet"
  - else
    %table#movies
      %thead
        %tr
          %th{class: ('hilite' if session[:sort_by] == 'title'), id: 'title_header'}= link_to('Movie Title', director_all_movies_path(:director => @director, sort_by: 'title', :from => (@from_movie_id unless @from_movie_id.nil?)))
          %th{class: ('hilite' if session[:sort_by] == 'director'), id: 'director_header'}= link_to('Director', director_all_movies_path(:director => @director, sort_by: 'director', :from => (@from_movie_id unless @from_movie_id.nil?)))
          %th{class: ('hilite' if session[:sort_by] == 'rating'), id: 'rating_header'}= link_to('Rating', director_all_movies_path(:director => @director, sort_by: 'rating', :from => (@from_movie_id unless @from_movie_id.nil?)))
          %th{class: ('hilite' if session[:sort_by] == 'release_date'), id: 'release_date_header'}= link_to('Release Date', director_all_movies_path(:director => @director, sort_by: 'release_date', :from => (@from_movie_id unless @from_movie_id.nil?)))
          %th More Info
      %tbody
        - @movies.each do |movie|
          %tr
            %td= movie.title
            %td= movie.director
            %td= movie.rating
            %td= movie.release_date
            %td= link_to "More about #{movie.title}", movie_path(movie)

- unless @from_movie_id.nil?
  = link_to "Back to #{@from_movie.title} page<br />".html_safe, movie_path(@from_movie_id)

= link_to 'Back to movie list<br />'.html_safe, movies_path

= @param_director
= @param_form
= @from_movie_id

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = render 'form', :movie => @movie

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

= form_tag movies_path, :method => :get, id: "ratings_form" do
  Include:
  - @rating_selected.keys.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", 1, @rating_selected[rating]
  = submit_tag 'Refresh', id:"ratings_submit"

= render 'list', :movies => @movies

= link_to 'Add new movie', new_movie_path

%h2 HW4 Zone
%h3 Main Features
%ul
  %li Make "director" RESTful
  %li Make all columns sortable
  %li Director's page has a "back to movie" link

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = render 'form', :movie => @movie

  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

= content_for(:title, @movie.title + ' - Rotten Potatoes!')

%h2 Details about #{@movie.title}

%ul#details
  %li
    Director:
    = @movie.director
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime('%B %d, %Y')

%h3 Description:

%p#description= @movie.description

-#- unless @director.nil?
= link_to "Find All Movies Directed by '#{@director}'", director_all_movies_path(@director, :from => @movie.id)
= '<br />'.html_safe

= link_to 'Edit', edit_movie_path(@movie)
= '<br />'.html_safe
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= '<br />'.html_safe
= link_to 'Back to movie list', movies_path
= '<br />'.html_safe